#!/bin/bash

# Requires
# PBX_MUMMER_PATH
# PBX_SCRIPTS_PATH
# PBX_WORKFLOW_PATH
# PBX_PROTOCOL_TEMPLATES_PATH
# PBX_PREASSEMBLY_RESULTS_PATH
# PBX_ASSEMBLY_RESULTS_PATH
# PBX_PREASSEMBLY_MIN_TRIMMED_PREASSEMBLED_READ_LENGTH
# PBX_PREASSEMBLY_MIN_TRIMMED_PREASSEMBLED_READ_QV

RESULTS_PATH=${PBX_ASSEMBLY_RESULTS_PATH}

mkdir -p ${RESULTS_PATH}

python2 ${PBX_SCRIPTS_PATH}/convert_fastq_to_fasta.py ${PBX_PREASSEMBLY_RESULTS_PATH}/data/corrected_${PBX_PREASSEMBLY_MIN_TRIMMED_PREASSEMBLED_READ_QV}_${PBX_PREASSEMBLY_MIN_TRIMMED_PREASSEMBLED_READ_LENGTH}.fastq ${RESULTS_PATH}/preassembled_reads.fasta y

cd ${RESULTS_PATH}

mkdir banks blast_contigs blast_singletons contigs singletons

parallel --env PBX_PROTOCOL_TEMPLATES_PATH --env PBX_MUMMER_PATH < ${PBX_WORKFLOW_PATH}/run_minimo_nucmer_preassembled.sh